<?php

/**
 * Implementation of hook_form_alter()
 */
function mymodule_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if ('comment_comment_form' == $form_id) {
        $form['actions']['submit']['#value'] = t('Please comment !');
    }
}

/**
 * Implementation of hook_theme()
 * 
 * @param type $existing
 * @param type $type
 * @param type $theme
 * @param type $path
 * @return type
 */


function mymodule_theme($existing, $type, $theme, $path) {
    return array(
        'custom_page_theme' => array(
            'variables' => array('page_data' => NULL),
            'template' => 'custom-page-theme',
        ),
    );
}

