<?php

function custom_form_theme() {
    return array(
        'abc_thumb_upload' => array('render element' => 'element'),
        
        'custom_block_template' => array(
            'variables' => array('title' => null, 'description' => null, 'data' => null),
            'template' => 'custom-block-template',
        ),
         'add_contact_form' => array('render element' => 'form', 'template' => 'add-contact-form',),
         
       
    );
}

/**

  function custom_form_preprocess_image_widget(&$variables) {
  $element = $variables['element'];
  $name = $element['#name'];
  // print_r($variables); die();

  $variables['attributes'] = array('class' => array('image-widget', 'js-form-managed-file', 'form-managed-file', 'clearfix'));

  if (!empty($element['fids']['#value'])) {

  $file = reset($element['#files']);

  $element['file_' . $file->id()]['filename']['#suffix'] = ' <span class="file-size">Ankit(' . format_size($file->getSize()) . ')</span> ';

  $file_variables = array(
  'style_name' => $element['#preview_image_style'],
  'uri' => $file->getFileUri(),
  );

  // Determine image dimensions.
  if (isset($element['#value']['width']) && isset($element['#value']['height'])) {
  $file_variables['width'] = $element['#value']['width'];
  $file_variables['height'] = $element['#value']['height'];
  } else {
  $image = \Drupal::service('image.factory')->get($file->getFileUri());
  if ($image->isValid()) {
  $file_variables['width'] = $image->getWidth();
  $file_variables['height'] = $image->getHeight();
  } else {
  $file_variables['width'] = $file_variables['height'] = NULL;
  }
  }

  $element['preview'] = array(
  '#weight' => -10,
  '#theme' => 'image_style',
  '#width' => $file_variables['width'],
  '#height' => $file_variables['height'],
  '#style_name' => $file_variables['style_name'],
  '#uri' => $file_variables['uri'],
  );

  // Store the dimensions in the form so the file doesn't have to be
  // accessed again. This is important for remote files.
  $element['width'] = array(
  '#type' => 'hidden',
  '#value' => $file_variables['width'],
  );
  $element['height'] = array(
  '#type' => 'hidden',
  '#value' => $file_variables['height'],
  );
  }

  $variables['data'] = array();
  foreach (\Drupal\Core\Render\Element::children($element) as $child) {
  $variables['data'][$child] = $element[$child];
  }
  }
 * 
 */


/**
function theme_abc_thumb_upload($variables) {

    $element = $variables['element']= 'ankit';

    if (isset($element['#file']->uri)) {
        $output = '<div id="edit-logo-ajax-wrapper"><div class="form-item form-type-managed-file form-item-logo"><span class="file">';
        $output .= 'ankit<img height="50px" src="' . file_create_url($element['#file']->uri) . '" />';
        $output .= '</span><input type="submit" id="edit-' . $element['#name'] . '-remove-button" name="' . $element['#name'] . '_remove_button" value="Remove" class="form-submit ajax-processed">';
        $output .= '<input type="hidden" name="' . $element['#name'] . '[fid]" value="' . $element['#file']->fid . '">';

        return $output;
    }
}
 *
 */
