<?php

function custom_form_schema(){
    $schema['custom_contact'] = array(
	'fields' => array(
	    'id'=> array(
		'type' => 'serial',
		'not null' => TRUE,
	    ),
	    'name' => array(
		'type' => 'varchar',
		'length' => 40,
		'not null' => TRUE,

	    ),
	    'message' => array(
		'type' => 'varchar',
		'length' => 255,
		'not null' => TRUE,
	    ),
	),
	 'primary key' => array('id'),
    );
    return $schema;
}